name : CI - PR Checks

on:
  pull_request:
    branches: [ main ]

jobs: 
    ci-checks:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.12'

        - name: Install dependencies
          run: pip install -r requirements.txt

        - name: Run tests
          run: flake8 app --max-line-length=120

        - name: Run tests
          run: pytest app/test_main.py -v